### ISSUE TITLE
cannot connect to API? 

### ISSUE THREAD

**Issue by tombenetin** [ecoen66/homebridge-solaredge-inverter#36]
Hi, i cannot receive values from SolarEdge inverter. I hide API, but in config is correct long API KEY of course. 
Thanks for any advice. 

Homebride .v1.5.0
Node.js Version | v14.20.0
homebridge-solaredge-inverter@0.2.7

```
[10/13/2022, 9:53:40 AM] Registering accessory 'homebridge-solaredge-inverter.SolarEdge Inverter'
    at createError (/usr/local/lib/node_modules/homebridge-solaredge-inverter/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-solaredge-inverter/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-solaredge-inverter/node_modules/axios/lib/adapters/http.js:293:11)
    url: 'https://monitoringapi.solaredge.com/site/homeserver/overview?api_key=HIDE_API_KEY',
      servername: 'monitoringapi.solaredge.com',
      _host: 'monitoringapi.solaredge.com',
      'Host: monitoringapi.solaredge.com\r\n' +
      responseUrl: 'https://monitoringapi.solaredge.com/site/homeserver/overview?api_key=HIDE_API_KEY',
    host: 'monitoringapi.solaredge.com',
      _currentUrl: 'https://monitoringapi.solaredge.com/site/homeserver/overview?api_key=HIDE_API_KEY',
      url: 'https://monitoringapi.solaredge.com/site/homeserver/overview?api_key=HIDE_API_KEY',
        'Host: monitoringapi.solaredge.com\r\n' +
      host: 'monitoringapi.solaredge.com',
```

config: 

```
        {
            "name": "SolarEdge Inverter",
            "manufacturer": "SolarEdge",
            "model": "Inverter",
            "serial": "solaredge-inverter-1",
            "site_id": "homeserver",
            "api_key": "HIDE",
            "update_interval": 15,
            "current": true,
            "currentWatts": true,
            "last_day": true,
            "last_month": true,
            "last_year": false,
            "life_time": true,
            "debug": true,
            "accessory": "SolarEdge Inverter"
        }
```

**Comment by Quickstep3** [comment]
your site id doesn't look right - it needs to be the site id from SolarEdge. You can get this from the installer or the App as well as the website it's usually a number.

**Comment by tombenetin** [comment]
yes you right, now it's working. Thanks
